resource_group_name         = "franc-resousce_group"
resource_group_location     = "East US 2"
virtual_network_name        = "vnet-devd"
pub-subnet_name             = "frontend-sub"
priv-subnet_name            = "backend-sub"
public_ip_name              = "publicip"
network_security_group_name = "nsg-dev1"
